language: python

python:
  - "3.4"
  - "3.5"

services:
  - mysql

install:
  - pip install -r requirements/test.txt

script:
  - py.test --cov-config .coveragerc maoaberta

after_success:
  - coverage report
  - coveralls
