language: python

python:
  - "3.4"
  - "3.5"

services:
  - mysql

install:
  - pip install -r requirements.txt

script:
  - coverage run --source=maoaberta maoaberta/manage.py test maoaberta

after_success:
  - coverage report
  - coveralls
